# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.12. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class TwofaRescue < Formula
  desc ""
  homepage "https://github.com/muquit/twofa-rescue"
  version "1.0.1"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-darwin-arm64.d.tar.gz"
    sha256 "6a5bc7167316fb589af6d58f899a4ca89abe2367dbe9b5f9b0c322610595946d"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-darwin-amd64.d.tar.gz"
    sha256 "fd380f9df15be1d8cc6063222f6a8f21f2673d0195a452ebf2be90c5fe9ea288"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-linux-amd64.d.tar.gz"
    sha256 "802fe64e922065072d1e08b00b903631ec210b2618ad2e45504940ab4b272561"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-linux-arm64.d.tar.gz"
    sha256 "bef06f2a6925b0232cac06436bc98137fdadb8dcb0e59c964c118d3769a42445"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "twofa-rescue-v#{version}-darwin-arm64" => "twofa-rescue"
      else
        bin.install "twofa-rescue-v#{version}-darwin-amd64" => "twofa-rescue"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "twofa-rescue-v#{version}-linux-arm64" => "twofa-rescue"
      else
        bin.install "twofa-rescue-v#{version}-linux-amd64" => "twofa-rescue"
      end
    end
  end
end
