# typed: false
# frozen_string_literal: true
# This file was generated by go-xbuild-go v1.0.12. DO NOT EDIT
# https://github.com/muquit/go-xbuild-go
class TwofaRescue < Formula
  desc ""
  homepage "https://github.com/muquit/twofa-rescue"
  version "1.0.1"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-darwin-arm64.d.tar.gz"
    sha256 "435433a11d90216f67e3b16f470a64be4de5df38b2832ac8ec0b3c890fed2ca5"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-darwin-amd64.d.tar.gz"
    sha256 "d3ed03357681023003dc3ed6e613e41df06da088986718fe1501a0d2880aa246"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-linux-amd64.d.tar.gz"
    sha256 "b49ff92e60bf8c61a83128e273858fe66bfc848cbb67af34d1adc19c34aac09e"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/muquit/twofa-rescue/releases/download/v1.0.1/twofa-rescue-v1.0.1-linux-arm64.d.tar.gz"
    sha256 "ce2dcd7aaa0e9b6e3482cd6f580514c37c3618d55482ea462da3b3e4dc7787c2"
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "twofa-rescue-v#{version}-darwin-arm64" => "twofa-rescue"
      else
        bin.install "twofa-rescue-v#{version}-darwin-amd64" => "twofa-rescue"
      end
    elsif OS.linux?
      if Hardware::CPU.arm?
        bin.install "twofa-rescue-v#{version}-linux-arm64" => "twofa-rescue"
      else
        bin.install "twofa-rescue-v#{version}-linux-amd64" => "twofa-rescue"
      end
    end
  end
end
